name: Sync fork with upstream
on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your fork
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Add upstream remote and fetch
        run: |
          git remote add upstream https://github.com/bitnami/containers.git
          git fetch upstream

      - name: Merge from upstream into local branch
        run: |
          git checkout main
          git merge upstream/main
          git push origin main

      - name: Clean up
        run: git remote remove upstream
